ALTER TABLE words
  ADD COLUMN IF NOT EXISTS image_bytes BYTEA NULL,
  ADD COLUMN IF NOT EXISTS image_mime TEXT NULL,
  ADD COLUMN IF NOT EXISTS audio_bytes BYTEA NULL,
  ADD COLUMN IF NOT EXISTS audio_mime TEXT NULL;

CREATE INDEX IF NOT EXISTS idx_words_term ON words (term);
